package me.saket.dank.utils;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class FileSizeUnitTest {

  private static final double TWO_FIFTY_MEGABYTES_IN_BYTES = 262_144_000d;
  private static final double TWO_FIFTY_MEGABYTES_IN_KILO_BYTES = 256_000d;
  private static final double TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES = 250d;
  private static final double TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES = 0.244140625d;
  private static final double DELTA = 0d;

  @Test
  public void poop() {
    assertEquals(FileSizeUnit.BYTES.toBytes(TWO_FIFTY_MEGABYTES_IN_BYTES), TWO_FIFTY_MEGABYTES_IN_BYTES, DELTA);
    assertEquals(FileSizeUnit.BYTES.toKiloBytes(TWO_FIFTY_MEGABYTES_IN_BYTES), TWO_FIFTY_MEGABYTES_IN_KILO_BYTES, DELTA);
    assertEquals(FileSizeUnit.BYTES.toMegaBytes(TWO_FIFTY_MEGABYTES_IN_BYTES), TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES, DELTA);
    assertEquals(FileSizeUnit.BYTES.toGigaBytes(TWO_FIFTY_MEGABYTES_IN_BYTES), TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES, DELTA);

    assertEquals(FileSizeUnit.KILOBYTES.toBytes(TWO_FIFTY_MEGABYTES_IN_KILO_BYTES), TWO_FIFTY_MEGABYTES_IN_BYTES, DELTA);
    assertEquals(FileSizeUnit.KILOBYTES.toKiloBytes(TWO_FIFTY_MEGABYTES_IN_KILO_BYTES), TWO_FIFTY_MEGABYTES_IN_KILO_BYTES, DELTA);
    assertEquals(FileSizeUnit.KILOBYTES.toMegaBytes(TWO_FIFTY_MEGABYTES_IN_KILO_BYTES), TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES, DELTA);
    assertEquals(FileSizeUnit.KILOBYTES.toGigaBytes(TWO_FIFTY_MEGABYTES_IN_KILO_BYTES), TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES, DELTA);

    assertEquals(FileSizeUnit.MEGABYTES.toBytes(TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES), TWO_FIFTY_MEGABYTES_IN_BYTES, DELTA);
    assertEquals(FileSizeUnit.MEGABYTES.toKiloBytes(TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES), TWO_FIFTY_MEGABYTES_IN_KILO_BYTES, DELTA);
    assertEquals(FileSizeUnit.MEGABYTES.toMegaBytes(TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES), TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES, DELTA);
    assertEquals(FileSizeUnit.MEGABYTES.toGigaBytes(TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES), TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES, DELTA);

    assertEquals(FileSizeUnit.GIGABYTES.toBytes(TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES), TWO_FIFTY_MEGABYTES_IN_BYTES, DELTA);
    assertEquals(FileSizeUnit.GIGABYTES.toKiloBytes(TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES), TWO_FIFTY_MEGABYTES_IN_KILO_BYTES, DELTA);
    assertEquals(FileSizeUnit.GIGABYTES.toMegaBytes(TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES), TWO_FIFTY_MEGABYTES_IN_MEGA_BYTES, DELTA);
    assertEquals(FileSizeUnit.GIGABYTES.toGigaBytes(TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES), TWO_FIFTY_MEGABYTES_IN_GIGA_BYTES, DELTA);
  }
}
